services:
  - type: web
    name: pksingh-backend
    env: node
    plan: free
    buildCommand: npm install && npx prisma db push && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: file:./dev.db
      - key: LOCAL_JWT_SECRET
        generateValue: true
      - key: NODE_VERSION
        value: "20.10.0"
